# Generated by Django 3.2.5 on 2021-08-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210731_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='faetured_images',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
