# Generated by Django 3.2.5 on 2021-08-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_faetured_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='faetured_images',
            new_name='featured_images',
        ),
    ]
